export const EventTypes = {
  // Business
  BUSINESS_CREATED: 'BUSINESS_CREATED',
  BUSINESS_UPDATED: 'BUSINESS_UPDATED',
  BUSINESS_DELETED: 'BUSINESS_DELETED',

  // Customer
  CUSTOMER_CREATED: 'CUSTOMER_CREATED',
  CUSTOMER_UPDATED: 'CUSTOMER_UPDATED',
  CUSTOMER_DELETED: 'CUSTOMER_DELETED',

  // Invoice
  INVOICE_CREATED: 'INVOICE_CREATED',
  INVOICE_UPDATED: 'INVOICE_UPDATED',
  INVOICE_SENT: 'INVOICE_SENT',
  INVOICE_OVERDUE: 'INVOICE_OVERDUE',
  INVOICE_PAID: 'INVOICE_PAID',

  // Payment
  PAYMENT_CREATED: 'PAYMENT_CREATED',
  PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',

  // Reminder
  REMINDER_CREATED: 'REMINDER_CREATED',
  REMINDER_SENT: 'REMINDER_SENT',
  REMINDER_FAILED: 'REMINDER_FAILED',

  // Recovery
  RECOVERY_STARTED: 'RECOVERY_STARTED',
  RECOVERY_ESCALATED: 'RECOVERY_ESCALATED',
  RECOVERY_COMPLETED: 'RECOVERY_COMPLETED',

  // Workflow
  WORKFLOW_STARTED: 'WORKFLOW_STARTED',
  WORKFLOW_COMPLETED: 'WORKFLOW_COMPLETED',

  // Rule
  RULE_EXECUTED: 'RULE_EXECUTED',

  // Automation
  AUTOMATION_STARTED: 'AUTOMATION_STARTED',
  AUTOMATION_COMPLETED: 'AUTOMATION_COMPLETED',

  // AI
  AI_RECOMMENDATION_CREATED: 'AI_RECOMMENDATION_CREATED',

  // Audit
  AUDIT_CREATED: 'AUDIT_CREATED',
} as const;

export type EventType =
  (typeof EventTypes)[keyof typeof EventTypes];
